name: Deploy on Railway
on:
    # Runs on pushes targeting the default branch
    push:
      branches: ["railway"]
  
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    
    schedule:
        - cron: "0 7 * * *"

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: lts/*
            - name: Install Packages
              run: npm install  
            - name: Checkout submodules
              run: git submodule update --init
            - name: Prepare Directory
              run: mkdir -p -v ./public/database/runways
            - name: Copy the submodule
              run: cp -R ./runways/icao/ ./public/database/runways/
            - name: Install Railway
              run: npm i -g @railway/cli
            - name: Deploy to Railway
              run: railway up
              env:
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
           
